export const MANUAL_REVIEW_STATUS_OPTIONS = [
  ['pass', '通过'],
  ['fail', '不通过'],
  ['unclear', '待确定'],
]

export const MANUAL_REVIEW_GROUP_LABELS = {
  opening_amount: '开标报价',
  bid_total_amount: '投标总金额',
  price_constraint: '招标最高限价',
  price_case_consistency: '直接报价大小写一致',
  price_limit_comparison: '是否超过最高限价',
  itemized_amount: '分项报价金额',
  itemized_total: '分项报价合计',
  template_segment: '附件模板一致性',
  attachment_result: '签字盖章日期',
}

export const MANUAL_REVIEW_KEY_LABELS = {
  amount_yuan: '金额（元）',
  amount: '金额',
  raw_amount: '金额原文',
  small_amount: '小写金额',
  capital_amount: '大写金额折算',
  capital_raw_amount: '大写金额原文',
  case_consistency_status: '大小写一致性',
  case_consistency_summary: '大小写一致性说明',
  keyword: '命中关键词',
  declared_total: '合计金额',
  quantity: '数量',
  unit_price: '单价',
  ocr_total: '原表格OCR小计',
  declared_line_total: '原表格OCR小计',
  calculated_total: '系统计算小计',
  expected_total: '系统计算小计',
  difference: '差额',
  row_status: '行算术校验',
  summary_status: '汇总一致性校验',
  missing_anchors: '缺失模板项',
  unfilled_fields: '未填写字段',
  signature_text: '签字识别内容',
  signature_texts: '签字识别内容',
  signature_evidence: '签字识别证据',
  seal_text: '盖章识别内容',
  seal_texts: '盖章识别内容',
  seal_evidence: '盖章识别证据',
  date_text: '落款日期',
  date: '落款日期',
  deadline_date: '最晚截止日期',
  deadline_text: '截止日期识别原文',
  deadline_page: '截止日期页码',
  matched_deadline_text: '截止日期识别原文',
  signature_status: '签字状态',
  signature_parse_status: '签字解析状态',
  seal_status: '盖章状态',
  date_status: '日期状态',
  status: '状态',
  result: '识别结论',
  summary: '识别摘要',
}

export const MANUAL_REVIEW_STATUS_LABELS = {
  pass: '通过',
  found: '通过',
  fail: '不通过',
  missing: '不通过',
  missing_date: '不通过',
  late: '不通过',
  not_required: '不要求',
  unparsed: '无法解析识别内容',
  parsed: '已解析',
  unclear: '待确定',
}
